baseurl: "" # the subpath of your site, e.g. /blog/
url: https://thecatseye.ca   # with the https protocol
enforce_ssl: thecatseye.ca   # without any protocol
maintenance: 0

#url: https://thecatseye.ca   # with the https protocol
#enforce_ssl: thecatseye.ca   # without any protocol

# Site settings
title: The Cat's Eye
email: "&#109;&#097;&#110;&#097;&#103;&#101;&#114;&#064;&#116;&#104;&#101;&#099;&#097;&#116;&#115;&#101;&#121;&#101;&#046;&#099;&#097;"
description: "The Cat's Eye is Victoria College's student-run lounge and pub. Come hang out with friends, study, or play games. The space is also available for booking for Victoria College groups."

# Color settings (hex-codes without the leading hash-tag)
# http://www.colorhexa.com/
color:
  primary: "660099"
  secondary: "440066"
  secondary-dark: 333

# Team names, titles and social links
exec:
- name: Darren Cheng
  pic: 1a
  position: Co-Manager

- name: Thomas Lynch
  pic: 2a
  position: Co-Manager

subcommittee:
 
- name: Rainbow Dash
  pic: 3
  
- name: Daring Do
  pic: 4

- name: Princess Cadance
  pic: 5

- name: Discord
  pic: 6

- name: Photo Finish
  pic: 7

- name: Twilight Sparkle
  pic: 8

- name: Starlight Glimmer
  pic: 9

- name: Applejack
  pic: 10

- name: Prim Hemline
  pic: 11

- name: Rarity
  pic: 12

- name: Sonata Dusk
  pic: 13

- name: Princess Luna
  pic: 14

- name: Sunset Shimmer
  pic: 15

- name: Prince Blueblood
  pic: 16

- name: King Sombra
  pic: 17

- name: Adagio Dazzle
  pic: 18

- name: Fluttershy
  pic: 19

- name: Pinkie Pie
  pic: 20

- name: Shining Armor
  pic: 21

- name: Aria Blaze
  pic: 22

- name: Lord Tirek
  pic: 23

- name: Princess Celestia
  pic: 24

- name: Sweetie Belle
  pic: 25

- name: Scootaloo
  pic: 26

- name: Babs Seed
  pic: 27

- name: Fancy Pants
  pic: 28

- name: Hoity Toity
  pic: 29

- name: Apple Bloom
  pic: 30

- name: Nightmare Moon
  pic: 31

- name: Princess Amore
  pic: 32

- name: Queen Chrysalis
  pic: 33

- name: Sapphire Shores
  pic: 34

- name: Trenderhoof
  pic: 35

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter-square
    url: http://twitter.com/viccatseye
  - title: facebook-square
    url: https://www.facebook.com/thecatseye
  - title: flickr
    url: https://www.flickr.com/photos/129567669@N05/
  - title: vimeo-square
    url: https://vimeo.com/thecatseye

# Postal address (add as many lines as necessary)
address:
  - line: Goldring Student Centre (Basement)
  - line: 150 Charles Street West
  - line: Toronto, ON, Canada
  - line: M5S 1K9

# Build settings
markdown: kramdown
permalink: pretty