baseurl: "" # the subpath of your site, e.g. /blog/
url: https://thecatseye.ca   # with the https protocol
enforce_ssl: thecatseye.ca   # without any protocol
maintenance: 0

# Site settings
title: The Cat's Eye
email: "&#109;&#097;&#110;&#097;&#103;&#101;&#114;&#064;&#116;&#104;&#101;&#099;&#097;&#116;&#115;&#101;&#121;&#101;&#046;&#099;&#097;"
description: "The Cat's Eye is Victoria College's student-run lounge and pub. Come hang out with friends, study, or play games. The space is also available for booking for Victoria College groups."

# Color settings (hex-codes without the leading hash-tag)
# http://www.colorhexa.com/
color:
  primary: "cc0099"
  secondary: "990073"
  secondary-dark: 333

# Team names, titles and social links
exec:
- name: Darren Cheng
  pic: CEDarrenC
  position: Senior Co-Manager

- name: Thomas Lynch
  pic: CEThomasL
  position: Junior Co-Manager

subcommittee:

- name: Aimee L
  pic: CEAimeeL

- name: Alisa M
  pic: 

- name: Alisha T
  pic: CEAlishaT

- name: Ana A
  pic: CEAnaA

- name: Apurva K
  pic: CEApurvaK

- name: Chelsea S
  pic: CEChelseaS

- name: Clara R
  pic: CEClaraR

- name: Daniel A
  pic: CEDanielA

- name: Daniel N
  pic: CEDanielN

- name: Darren C
  pic: CEDarrenC

- name: Diana V
  pic: CEDianaV

- name: Edward D
  pic: CEEdwardD

- name: Elly G
  pic: CEEllyG

- name: Fosta S
  pic: CEFostaS

- name: Gabrielle G
  pic: 

- name: Garnet L
  pic: CEGarnetL

- name: Hannah B
  pic: CEHannahB

- name: Isidora A
  pic: CEIsidoraA

- name: Jacob K
  pic: CEJacobK

- name: Jahnavi S
  pic: CEJahnaviS

- name: Julia G
  pic: CEJuliaG

- name: Juliana J
  pic: 

- name: Katie P
  pic: CEKatieP

- name: Madison L
  pic: CEMadisonL

- name: Mercer P
  pic: CEMercerP

- name: Nicole C
  pic: CENicoleC

- name: Nicole G
  pic: CENicoleG

- name: Ryan F
  pic: CERyanF

- name: Seraphina V
  pic: CESeraphinaV

- name: Sharon W
  pic: CESharonW

- name: Stefan V
  pic: CEStefanV

- name: Sudarshan B
  pic: CESudarshanB

- name: Thomas L
  pic: CEThomasL

- name: Wenting P
  pic: CEWentingP

- name: Zayneb R
  pic: CEZaynebR

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter-square
    url: http://twitter.com/viccatseye
  - title: facebook-square
    url: https://www.facebook.com/thecatseye
  - title: flickr
    url: https://www.flickr.com/photos/129567669@N05/
  - title: vimeo-square
    url: https://vimeo.com/thecatseye

# Postal address (add as many lines as necessary)
address:
  - line: Goldring Student Centre (Basement)
  - line: 150 Charles Street West
  - line: Toronto, ON, Canada
  - line: M5S 1K9

# Build settings
markdown: kramdown
permalink: pretty
