baseurl: "" # the subpath of your site, e.g. /blog/
url: https://thecatseye.ca   # with the https protocol
enforce_ssl: thecatseye.ca   # without any protocol
maintenance: 0

# Site settings
title: The Cat's Eye
email: "&#109;&#097;&#110;&#097;&#103;&#101;&#114;&#064;&#116;&#104;&#101;&#099;&#097;&#116;&#115;&#101;&#121;&#101;&#046;&#099;&#097;"
description: "The Cat's Eye is Victoria College's student-run lounge and pub. Come hang out with friends, study, or play games. The space is also available for booking for Victoria College groups."

# Color settings (hex-codes without the leading hash-tag)
# http://www.colorhexa.com/
color:
  primary: "cc0099"
  secondary: "990073"
  secondary-dark: 333

# Team names, titles and social links
exec:
- name: Berenice Alvarez
  pic: berenice
  position: Senior Co-Manager

- name: Maxwell Nisbeth
  pic: maxwell
  position: Junior Co-Manager

subcommittee:

- name: Abera
  pic:  Abera 

- name: Ali
  pic:  ali

- name: Aloysius
  pic:  Aloysius

- name: Ana
  pic:  Ana

- name: Anna
  pic:  Anna

- name: Ashley
  pic:  ashley

- name: Ashley F.
  pic:  Ashley_fung

- name: Aya
  pic:  Aya

- name: Caitie
  pic:  Catie

- name: Chris
  pic:  Chris

- name: Cindy
  pic:  Cindy

- name: Cy
  pic:  Cy

- name: Emily
  pic:  Emily

- name: Erin
  pic:  Erin

- name: Eugene
  pic:  Eugene

- name: Gabby
  pic:  gabby

- name: Helen
  pic:  Helen

- name: Isha
  pic:  isha

- name: Isidora
  pic:  isidora

- name: James
  pic:  James

- name: Katie
  pic:  katie

- name: Kevin
  pic:  Kevin

- name: Landon
  pic:  Landon

- name: Masha
  pic:  Masha

- name: Melinda
  pic:  Melinda

- name: Michael
  pic:  Micheal

- name: Nicole
  pic:  nicole

- name: Rachel
  pic:  Rachel

- name: Sara
  pic:  Sara

- name: Sarah
  pic:  Sarah

- name: Siobhan
  pic:  Siobhan

- name: Tanuj
  pic:  tanuj

- name: Zach
  pic:  Zach

# Carousel images (add as many lines as necessary)
carousel:
- index: 0
  pic: img/header-short7.png #The Cat's Eye Banner Image
- index: 1
  pic: img/carousel/1.jpg
- index: 2
  pic: img/carousel/2.jpg
- index: 3
  pic: img/carousel/3.jpg
- index: 4
  pic: img/carousel/4.jpg
- index: 5
  pic: img/carousel/5.jpg

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter-square
    url: https://twitter.com/viccatseye
  - title: facebook-square
    url: https://www.facebook.com/thecatseye
  - title: flickr
    url: https://www.flickr.com/photos/129567669@N05
  - title: vimeo-square
    url: https://vimeo.com/thecatseye
  - title: instagram
    url: https://www.instagram.com/viccatseye

# Postal address (add as many lines as necessary)
address:
  - line: Goldring Student Centre (Basement)
  - line: 150 Charles Street West
  - line: Toronto, ON, Canada
  - line: M5S 1K9

# Past managers (add as many lines as necessary)
# Newest to oldest
past_managers:
  - name: Ali Kehl
  - name: Zayneb Ragheai
  - name: Jordan LoMonaco
  - name: Thomas Lynch
  - name: Darren Cheng
  - name: Sabina Freiman
  - name: Sadia Awan
  - name: Karl Cadonic
  - name: Lucas Fejes
  - name: Katrina Vogan
  - name: Megan Tangney
  - name: Naomi Lam 
  - name: Savannah Sloat 
  - name: Kenny Zhan 
  - name: Sonya Snyder
  - name: Adam Malek
  - name: Brandon Bailey
  - name: Carlo Vinco
  - name: Matt Thorpe 
  - name: Nader Farhat 
  - name: Nick Kelly

# Build settings
markdown: kramdown
permalink: pretty
