baseurl: "" # the subpath of your site, e.g. /blog/
url: https://thecatseye.ca   # with the https protocol
enforce_ssl: thecatseye.ca   # without any protocol
maintenance: 0

# Site settings
title: The Cat's Eye
email: "&#109;&#097;&#110;&#097;&#103;&#101;&#114;&#064;&#116;&#104;&#101;&#099;&#097;&#116;&#115;&#101;&#121;&#101;&#046;&#099;&#097;"
description: "The Cat's Eye is Victoria College's student-run lounge and pub. Come hang out with friends, study, or play games. The space is also available for booking for Victoria College groups."

# Color settings (hex-codes without the leading hash-tag)
# http://www.colorhexa.com/
color:
  primary: "660099"
  secondary: "440066"
  secondary-dark: 333

# Team names, titles and social links
exec:
- name: Darren Cheng
  pic: 1a
  position: Co-Manager

- name: Thomas Lynch
  pic: 2a
  position: Co-Manager

subcommittee:
 
- name: Aimee L
  pic: 3
  
- name: Alisa M
  pic: 4

- name: Alisha T
  pic: 5

- name: Ana A
  pic: 6

- name: Apurva K
  pic: 7

- name: Chelsea S
  pic: 8

- name: Clara R
  pic: 9

- name: Daniel A
  pic: 10

- name: Daniel N
  pic: 11

- name: Diana V
  pic: 12

- name: Edward D
  pic: 13

- name: Elly G
  pic: 14

- name: Fosta S
  pic: 15

- name: Gabrielle G
  pic: 16

- name: Garnet L
  pic: 17

- name: Hannah B
  pic: 18

- name: Isidora A
  pic: 19

- name: Jacob K
  pic: 20

- name: Jahnavi S
  pic: 21

- name: Julia G
  pic: 22

- name: Juliana J
  pic: 23

- name: Katie P
  pic: 24

- name: Madison L
  pic: 25

- name: Mercer P
  pic: 26

- name: Nicole C
  pic: 27

- name: Nicole G
  pic: 28

- name: Ryan F
  pic: 29

- name: Seraphina V
  pic: 30

- name: Sharon W
  pic: 31

- name: Stefan V
  pic: 32

- name: Sudarshan B
  pic: 33

- name: Wenting P
  pic: 34

- name: Zayneb R
  pic: 35

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter-square
    url: http://twitter.com/viccatseye
  - title: facebook-square
    url: https://www.facebook.com/thecatseye
  - title: flickr
    url: https://www.flickr.com/photos/129567669@N05/
  - title: vimeo-square
    url: https://vimeo.com/thecatseye

# Postal address (add as many lines as necessary)
address:
  - line: Goldring Student Centre (Basement)
  - line: 150 Charles Street West
  - line: Toronto, ON, Canada
  - line: M5S 1K9

# Build settings
markdown: kramdown
permalink: pretty