baseurl: "" # the subpath of your site, e.g. /blog/
url: https://thecatseye.ca   # with the https protocol
enforce_ssl: thecatseye.ca   # without any protocol
maintenance: 0

# Site settings
title: The Cat's Eye
email: "&#109;&#097;&#110;&#097;&#103;&#101;&#114;&#064;&#116;&#104;&#101;&#099;&#097;&#116;&#115;&#101;&#121;&#101;&#046;&#099;&#097;"
description: "The Cat's Eye is Victoria College's student-run lounge and pub. Come hang out with friends, study, or play games. The space is also available for booking for Victoria College groups."

# Color settings (hex-codes without the leading hash-tag)
# http://www.colorhexa.com/
color:
  primary: "cc0099"
  secondary: "990073"
  secondary-dark: 333

# Team names, titles and social links
exec:
- name: Jordan LoMonaco
  pic: CEJordanL
  position: Senior Co-Manager

- name: Zayneb Ragheai
  pic: CEZaynebR
  position: Junior Co-Manager

subcommittee:

- name: Aimee
  pic:  aimee.jpg 

- name: Ali
  pic:  ali.jpg

- name: Anthony
  pic:  anthony.jpg

- name: Artimes
  pic:  artimes.jpg

- name: Ashley
  pic:  ashley.jpg

- name: Berenice
  pic:  berenice.jpg

- name: Brandon
  pic:  brandon.jpg 

- name: Dimitri
  pic:  dimitri.jpg

- name: Elly
  pic:  elly.jpg

- name: Emma
  pic:  emma.jpg

- name: Gabby
  pic:  gabby.jpg

- name: Gem
  pic:  gem.jpg

- name: Ibaa
  pic:  ibaa.jpg

- name: Ioana
  pic:  ioana.jpg

- name: Isha
  pic:  isha.jpg

- name: Isidora
  pic:  isidora.jpg

- name: Julia
  pic:  julia.jpg

- name: Katie
  pic:  katie.jpg

- name: Keely
  pic:  keely.jpg

- name: Kyle
  pic:  kyle.jpg

- name: Liam F
  pic:  liam_f.jpg

- name: Liam T
  pic:  liam_t.jpg

- name: Lim
  pic:  lim.jpg

- name: Madelaine
  pic:  madelaine.jpg

- name: Marjan
  pic:  marjan.jpg

- name: Nicole
  pic:  nicole.jpg

- name: Sharon
  pic:  sharon.jpg

- name: Stefan
  pic:  stefan.jpg

- name: Steve
  pic:  steve.jpg

- name: Suzanne
  pic:  suzanne.jpg

- name: Tanuj
  pic:  tanuj.jpg

- name: Taylor
  pic:  taylor.jpg

- name: Zach
  pic:  zach.jpg

- name: Zoe K
  pic:  zoe_k.jpg

- name: Zoe R
  pic:  zoe_r.jpg

# Carousel images (add as many lines as necessary)
carousel:
- index: 0
  pic: img/header-short7.png #The Cat's Eye Banner Image
- index: 1
  pic: img/carousel/1.jpg
- index: 2
  pic: img/carousel/2.jpg
- index: 3
  pic: img/carousel/3.jpg
- index: 4
  pic: img/carousel/4.jpg
- index: 5
  pic: img/carousel/5.jpg

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter-square
    url: https://twitter.com/viccatseye
  - title: facebook-square
    url: https://www.facebook.com/thecatseye
  - title: flickr
    url: https://www.flickr.com/photos/129567669@N05
  - title: vimeo-square
    url: https://vimeo.com/thecatseye
  - title: instagram
    url: https://www.instagram.com/viccatseye

# Postal address (add as many lines as necessary)
address:
  - line: Goldring Student Centre (Basement)
  - line: 150 Charles Street West
  - line: Toronto, ON, Canada
  - line: M5S 1K9

# Past managers (add as many lines as necessary)
# Newest to oldest
past_managers:
  - name: Thomas Lynch
  - name: Darren Cheng
  - name: Sabina Freiman
  - name: Sadia Awan
  - name: Karl Cadonic
  - name: Lucas Fejes
  - name: Katrina Vogan
  - name: Megan Tangney
  - name: Naomi Lam 
  - name: Savannah Sloat 
  - name: Kenny Zhan 
  - name: Sonya Snyder
  - name: Adam Malek
  - name: Brandon Bailey
  - name: Carlo Vinco
  - name: Matt Thorpe 
  - name: Nader Farhat 
  - name: Nick Kelly

# Build settings
markdown: kramdown
permalink: pretty
