url: "https://ryanfan.github.io"
baseurl: "/cats-eye-revamped/"

# Site settings
title: The Cat's Eye
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
# http://www.colorhexa.com/
color:
  primary: "cc3366"
  secondary: "a32952"
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Darren Cheng
  pic: 1
  position: Co-Manager
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #
    - title: envelope
      url: #

- name: Thomas Lynch
  pic: 2
  position: Co-Manager
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #
    - title: envelope
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/viccateseye
  - title: facebook
    url: https://www.facebook.com/thecatseye
  - title: flickr
    url: https://www.flickr.com/photos/129567669@N05/sets/

# Postal address (add as many lines as necessary)
address:
  - line: Goldring Student Centre (Basement)
  - line: 150 Charles Street West
  - line: Toronto, ON, Canada
  - line: M5S 1K9

# Build settings
markdown: kramdown
permalink: pretty