url: "https://ryanfan.github.io"
baseurl: "/cats-eye-revamped/"

# Site settings
title: The Cat's Eye
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
# http://www.colorhexa.com/
color:
  primary: "660099"
  secondary: "440066"
  secondary-dark: 333

# Team names, titles and social links
exec:
- name: Darren Cheng
  pic: 1a
  position: Co-Manager

- name: Thomas Lynch
  pic: 2a
  position: Co-Manager

subcommittee:
 
- name: RainbowDash
  pic: 3
  
- name: DaringDo
  pic: 4

- name: PrincessCadance
  pic: 5

- name: Discord
  pic: 6

- name: PhotoFinish
  pic: 7

- name: TwilightSparkle
  pic: 8

- name: StarlightGlimmer
  pic: 9

- name: Applejack
  pic: 10

- name: PrimHemline
  pic: 11

- name: Rarity
  pic: 12

- name: SonataDusk
  pic: 13

- name: PrincessLuna
  pic: 14

- name: SunsetShimmer
  pic: 15

- name: PrinceBlueblood
  pic: 16

- name: KingSombra
  pic: 17

- name: AdagioDazzle
  pic: 18

- name: Fluttershy
  pic: 19

- name: PinkiePie
  pic: 20

- name: ShiningArmor
  pic: 21

- name: AriaBlaze
  pic: 22

- name: LordTirek
  pic: 23

- name: PrincessCelstia
  pic: 24

- name: SweetieBelle
  pic: 25

- name: Scootaloo
  pic: 26

- name: BabsSeed
  pic: 27

- name: FancyPants
  pic: 28

- name: HoityToity
  pic: 29

- name: AppleBloom
  pic: 30

- name: NightmareMoon
  pic: 31

- name: PrincessAmore
  pic: 32

- name: QueenChrysalis
  pic: 33

- name: SapphireShores
  pic: 34

- name: Trenderhoof
  pic: 35

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter-square
    url: http://twitter.com/viccatseye
  - title: facebook-square
    url: https://www.facebook.com/thecatseye
  - title: flickr
    url: https://www.flickr.com/photos/129567669@N05/
  - title: vimeo-square
    url: https://vimeo.com/thecatseye

# Postal address (add as many lines as necessary)
address:
  - line: Goldring Student Centre (Basement)
  - line: 150 Charles Street West
  - line: Toronto, ON, Canada
  - line: M5S 1K9

# Build settings
markdown: kramdown
permalink: pretty